version: '3.8'

services:
  juego:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DISPLAY=:0  # Si necesitas usar la pantalla del host
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  
networks:
  monitoring:
    driver: bridge
